// Auto-generated by train_centroid.py (per-feature scales)
#pragma once
#include <stdint.h>

#define FEAT_DIM 4
static const int32_t FEAT_SCALES[FEAT_DIM] = { 52759, 4214, 2769, 9 };
static const int32_t MU_INT[FEAT_DIM] = { 3484, 1765, 8023, 10782 };
static const uint64_t DIST2_THRESH = 100446235ULL;
// Feature order: rms, ptp, kurtosis, dominant_hz
